
//文章
export const REQUEST_ARTICLE_LIST = 'REQUEST_ARTICLE_LIST';
export const FETCH_ARTICLE_LIST = 'FETCH_ARTICLE_LIST';
export const RECEIVE_ARTICLE_LIST = 'RECEIVE_ARTICLE_LIST';

//类型按钮
export const REQUEST_TYPE_LIST = 'REQUEST_TYPE_LIST';
export const FETCH_TYPE_LIST = 'FETCH_TYPE_LIST';
export const RECEIVE_TYPE_LIST = 'RECEIVE_TYPE_LIST';

//新闻
export const REQUEST_NEWS_LIST = 'REQUEST_NEWS_LIST';
export const FETCH_NEWS_LIST = 'FETCH_NEWS_LIST';
export const RECEIVE_NEWS_LIST = 'RECEIVE_NEWS_LIST';



//repo
export const REQUEST_REPO_LIST = 'REQUEST_REPO_LIST';
export const FETCH_REPO_LIST = 'FETCH_REPO_LIST';
export const RECEIVE_REPO_LIST = 'RECEIVE_REPO_LIST';
